from pydantic import BaseModel


class LLMRequest(BaseModel):
    """
    Represents a request for language model processing.

    Attributes:
        text (str): The input text to be processed by the language model.
    """

    text: str


class LLMResponse(BaseModel):
    """
    Represents the response from a language model.

    Attributes:
        text (str): The output text generated by the language model.
    """

    text: str

