from pydantic import BaseModel


class TrainingRequest(BaseModel):
    """
    Represents a request for language model training.

    Attributes:
        start_context (str): The initial input context to be processed by the language model.
        learning_rate (float): The learning rate used during the training process.
        num_epoch (int): The number of epochs to train the language model.
    """

    start_context: str
    learning_rate: float
    num_epoch: int



class TrainingResponse(BaseModel):
    """
    Represents the response from a language model.

    Attributes:
        text (str): The output text generated by the language model.
    """

    text: str

